<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dsl</string>
		<string>DSL</string>
	</array>
	<key>name</key>
	<string>Jenkins DSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>New variable definitions like def</string>
			<key>match</key>
			<string>(def|job)</string>
			<key>name</key>
			<string>storage.type.def.dsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>("""|''')</string>
			<key>end</key>
			<string>("""|''')</string>
			<key>name</key>
			<string>string.quoted.triple.dsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>end</key>
			<string>(')</string>
			<key>name</key>
			<string>string.quoted.single.dsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>end</key>
			<string>(")</string>
			<key>name</key>
			<string>string.quoted.double.dsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|\-\&gt;)</string>
			<key>name</key>
			<string>keyword.operator.assignment.dsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(===|==|!=|&lt;=|&gt;=|&lt;=&gt;|&lt;&gt;|&lt;|&gt;|&lt;&lt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.dsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|&amp;&amp;|\+|\\|\\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.dsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(return|break|continue|default|do|while|for|switch|if |else)</string>
			<key>name</key>
			<string>keyword.control.dsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:sprintf|print(?:f|ln)?)</string>
			<key>name</key>
			<string>support.function.print.dsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true|false|null|node \/|node \-&gt;)</string>
			<key>name</key>
			<string>constant.language.dsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(//)</string>
			<key>end</key>
			<string>(\n)</string>
			<key>name</key>
			<string>comment.line.double-slash.dsl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dsl</string>
	<key>uuid</key>
	<string>a0b67aa6-2294-46b8-a7d2-b18f6bc61db1</string>
</dict>
</plist>
